config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  
  root 'questions#index'

  devise_scope :user do
    post '/auth/register' => 'omniauth_callbacks#sign_up'
  end

  namespace :api do
    namespace :v1 do
      resources :profiles, only: :index do
        get :me, on: :collection
      end

      resources :questions, only: %i[index create show], shallow: true do
        resources :answers, only: %i[show create index]
      end
    end
  end

  resources :subscriptions, only: %i[create destroy]

  concern :votes do
    post :vote_for, on: :member
    post :vote_against, on: :member
    post :reset_vote, on: :member
  end

  concern :comments do
    resources :comments,  only: [:create]
  end

  resources :questions, shallow: true, concerns: [:votes, :comments]  do
    resources :answers, only: %i[destroy create update], concerns: [:votes, :comments] do
      post :best_answer, on: :member
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  # setup connection with the server
  mount ActionCable.server => '/cable'

  get 'search', to: 'search#search'

  # default_url_options Rails.application.config.action_mailer.default_url_options
end

app/models/search.rb
class Search
  SEARCHING_CATEGORIES = %w[Question Answer Comment User]

  def self.search(query, search_category = nil)
    secure_query = ThinkingSphinx::Query.escape(query)
    if SEARCHING_CATEGORIES.include?(search_category)
      model = search_category.classify.constantize
      model.search secure_query
    else
      ThinkingSphinx.search secure_query
    end
  end
end

app/controllers/search_controller.rb
# require '/Users/mnogtieva/Learning/thinknetica/qna/app/presenters/searches/search_presernter.rb'
require "#{Rails.root}/app/presenters/searches/search_presernter.rb" 
class SearchController < ApplicationController
  skip_authorization_check 
  def search
    @search_results = Search.search(params[:search][:query], params[:search][:category])  if params[:search][:query].present?
  end
end

app/views/search/_answer_comments_result.html.slim
li
  = link_to result.body, question_path(result.commentable.question)

app/views/search/_answers_search_result.html.slim
li
  = link_to result.body, result.question

app/views/search/_form.html.slim
= form_for :search, url: search_path, method: :get do |f|
  = f.text_field :query
  = f.select :category, Search::SEARCHING_CATEGORIES, { include_blank: 'All' }, { class: 'form-control' }
  = f.submit 'Search'

app/views/search/_question_comments_result.html.slim
li
  = link_to result.body, question_path(result.commentable_id)

app/views/search/_questions_search_result.html.slim
li
  = link_to result.title, result

app/views/search/_users_search_result.html.slim
li
  = result.email

app/views/search/search.html.slim
h2 Search Results

.results
  ul
  - present(@search_results, ::Searches::SearchPresenter) do |search_results_presenter|
    = search_results_presenter.render_results