config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  
  root 'questions#index'

  devise_scope :user do
    post '/auth/register' => 'omniauth_callbacks#sign_up'
  end

  namespace :api do
    namespace :v1 do
      resources :profiles, only: :index do
        get :me, on: :collection
      end

      resources :questions, only: %i[index create show], shallow: true do
        resources :answers, only: %i[show create index]
      end
    end
  end

  resources :subscriptions, only: %i[create destroy]

  concern :votes do
    post :vote_for, on: :member
    post :vote_against, on: :member
    post :reset_vote, on: :member
  end

  concern :comments do
    resources :comments,  only: [:create]
  end

  resources :questions, shallow: true, concerns: [:votes, :comments]  do
    resources :answers, only: %i[destroy create update], concerns: [:votes, :comments] do
      post :best_answer, on: :member
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  # setup connection with the server
  mount ActionCable.server => '/cable'

  get 'search', to: 'search#search'

  # default_url_options Rails.application.config.action_mailer.default_url_options
end

app/models/answer.rb
class Answer < ApplicationRecord
  include Voting
  include Commenting
  
  belongs_to :question, touch: true
  belongs_to :user
  has_many :attachments, as: :attachable, dependent: :destroy
  has_many :votes, as: :votable, dependent: :destroy

  validates :body, presence: true
  
  accepts_nested_attributes_for :attachments, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :votes, reject_if: :all_blank, allow_destroy: true
  
  after_create :notify_about_new_answer, on: :create

  scope :sort_by_best, -> { order(best: :desc) }

  def mark_best
    transaction do
      question.answers.update_all(best: false)
      reload.update!(best: true)
    end
  end

  def notify_about_new_answer
    NewAnswerNotificationJob.perform_later(self)
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  
  include VoteAction
  before_action :authenticate_user!
  before_action :load_question, only: %i[create]
  before_action :load_answer, only: %i[destroy update best_answer ]
  after_action :publish_answer, only: %i[create]

  authorize_resource

  respond_to  :js

  def create
    @answer = current_user.answers.new(answer_params.merge(question_id: @question.id))
    respond_with(@answer.save)
  end

  def destroy
    respond_with(@answer.destroy)  if current_user.author_of?(@answer)
  end

  def update
    @answer.update(answer_params) if current_user.author_of?(@answer)
    respond_with(@answer)
  end

  def best_answer 
    @answer.mark_best if current_user.author_of?(@answer.question)
  end

  private
  def publish_answer
    return if @answer.errors.any?
    attachments = @answer.attachments.map do |attach|
      { id: attach.id, filename: attach.file.filename, url: attach.file.url }
    end
    data = @answer.as_json(include: :attachments).merge(answer: @answer, 
                                                        voted: @answer.voted?(current_user), 
                                                        vote_score: @answer.vote_score)


    ActionCable.server.broadcast("questions_#{@question.id}", 
      data: data
    )
  end

  def load_question
    @question = Question.find(params[:question_id])
  end

  def load_answer
    @answer = Answer.find(params[:id])
    @question = @answer.question
  end

  def answer_params
    params.require(:answer).permit(:body, attachments_attributes: [:file, :id, :_destroy])
  end
end

app/controllers/api/v1/answers_controller.rb
class Api::V1::AnswersController < Api::V1::BaseController
  authorize_resource

  before_action :load_question, only: %i[index create]

  def index
    respond_with @question.answers
  end

  def show
    @answer = Answer.find(params[:id])
    respond_with @answer
  end

  def create
    @answer = Answer.create(answer_params.merge(user: current_resource_owner, question: @question))
    respond_with @answer
  end


  private

  def load_question
    @question = Question.find(params[:question_id])
  end

  def answer_params
    params.require(:answer).permit(:body)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.slim
- cache answer do
  div id="answer-id-#{answer.id}" class="#{'best-answer' if answer.best?}"
    p id="#answer-errors-#{@answer.id}"
    p= answer.body
    =render 'common/attachment_list', resource: answer
    =render 'common/votes', resource: answer

    p= answer.updated_at.to_s
    - if can?(:update, answer)
      div
        div#messages
        p= link_to 'Delete Answer',answer , remote: true, method: :delete, data: { confirm: "Are you sure you wnt to delete this answer?" }
        p= link_to 'Edit Answer', nil, class: 'edit-answer-link', data: {answer_id: answer.id}

        =form_for answer, remote: true do |f|
          div id="answer-errors-#{answer.id}"
          = f.label :body, 'Edit Your Answer'
          = f.text_area :body
          = render 'common/edit_attachment_form', f: f
          = link_to 'Cancel', nil, data: { 'cancel-edit-id': answer.id }, class: 'btn-cancel-edit-answer'
          = f.submit 'Save', class: 'btn-save-updated-answer'
    - if can?(:best_answer, answer)
        p= button_to 'Best Answer', best_answer_answer_path(answer), remote: true

    =render 'common/comments', resource: answer

app/views/answers/best_answer.js.erb
$('.answers').html('<%= j render @question.answers.sort_by_best%>')

app/views/answers/create.js.erb
<% if @answer.errors.present? %>
  <% @answer.errors.full_messages.each do |message| %>
    $('#answer-errors').html('<%= j message %>');
  <% end %>
<% else %>
  $('#answer_body').val('');
  $('.answers').append('<%= j render @answer %>');
  $('#errors').html('');
<%end%>

app/views/answers/destroy.js.erb
 $('#answer-id-<%= @answer.id %>').remove()

app/views/answers/errors.js.erb
$('#errors').html('<%= j render 'common/errors', resource: @answer %>');

app/views/answers/update.js.erb
<% if @answer.errors.present? %>
  <% @answer.errors.full_messages.each do |message| %>
    $('#answer-errors-<%= @answer.id %>').html('<%= j message %>');
  <% end %>
<% else %>
  $('#answer-id-<%= @answer.id %>').html('<%= j render @answer %>');
<% end %>