config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  
  root 'questions#index'

  devise_scope :user do
    post '/auth/register' => 'omniauth_callbacks#sign_up'
  end

  namespace :api do
    namespace :v1 do
      resources :profiles, only: :index do
        get :me, on: :collection
      end

      resources :questions, only: %i[index create show], shallow: true do
        resources :answers, only: %i[show create index]
      end
    end
  end

  resources :subscriptions, only: %i[create destroy]

  concern :votes do
    post :vote_for, on: :member
    post :vote_against, on: :member
    post :reset_vote, on: :member
  end

  concern :comments do
    resources :comments,  only: [:create]
  end

  resources :questions, shallow: true, concerns: [:votes, :comments]  do
    resources :answers, only: %i[destroy create update], concerns: [:votes, :comments] do
      post :best_answer, on: :member
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  # setup connection with the server
  mount ActionCable.server => '/cable'

  get 'search', to: 'search#search'

  # default_url_options Rails.application.config.action_mailer.default_url_options
end

app/views/common/_attachement_form.html.slim
= f.label :files
= f.file_field :files, multiple: true

app/views/common/_attachment_list.html.slim
-if resource.attachments.present?
  p Attachments:
  ul
    - resource.attachments.each do |a| 
      li= link_to a.file.filename, a.file.url

app/views/common/_comments.html.slim
h6.header-title Comments
.comments data-id="#{resource.id}"
  .all-comments
    - if resource.comments.present?

    - resource.comments.each do |comment|
      - cache do
          div
              p.comment-body= comment.body
              p.user-email= comment.user.email
              p.comment-date= comment.updated_at
  -if can?(:comment, resource)
    - cache ['comment_form', resource] do
      = form_for [resource, resource.comments.build], remote: true, data: { type: :json } do |f|
        = f.text_area :body, class: 'form-control item-comment'
        = f.submit 'Place a comment', class: 'btn-comment'

app/views/common/_edit_attachment_form.html.slim
.form-group
  = f.fields_for :attachments do |attach|
    .nested-fields
      p
        => attach.object.file.filename
        = link_to_remove_association 'remove file', attach

  = link_to_add_association 'add file', f, :attachments, partial: 'common/file_fields'

app/views/common/_errors.html.slim
- if resource.present? && resource.errors.any?
  div.errors
    ul
      - resource.errors.full_messages.each do |message|
        li= message

app/views/common/_file_fields.html.slim
.nested-fields
  = f.label :file
  = f.file_field :file

app/views/common/_questions_list.html.slim
.question-item
  h4=  link_to question.title, question_path(question)
  p= question.body

app/views/common/_subscription.html.slim
.subscription
  - if can?(:create, Subscription) && !current_user.subscribed?(@question) && !current_user.author_of?(@question)
    p= button_to 'Subscribe', subscriptions_path(question_id: @question), remote: true
- @question.subscriptions.each do |subscription|
  - if can?(:destroy, subscription)
    p= button_to 'Unsubscribe', subscription_path(subscription), method: :delete, remote: true

app/views/common/_votes.html.slim
.vote data-id="#{resource.id}"
  - if can?(:vote, resource)
   .vote-for= button_to '+', { remote: true, data: { type: :json } }, { class: 'vote-for-btn ' "#{'hide' if resource.voted?(current_user)}" }
   .vote-score= resource.vote_score
   .vote-against= button_to '-', { remote: true, data: { type: :json } }, { class: 'vote-against-btn ' "#{'hide' if resource.voted?(current_user)}" }
   - if can?(:reset_vote, resource)
   .reset-vote= button_to 'Reset Vote', { remote: true, data: { type: :json } }, { class: 'reset-vote-btn ' "#{'hide' unless resource.voted?(current_user)}" }
  - else
   .vote-score= resource.vote_score

app/views/common/confirm_mail.html.slim
= form_tag auth_register_path, method: :post do
  .form-group
     = label_tag 'auth[info][email]', 'Email'
     = email_field 'auth[info]', :email

  = submit_tag 'Confirm email'

app/views/common/messages.js.erb
$('#messages').html('');

app/views/common/subscribe.js.erb
$('.subscription').html('<%= j render 'common/subscription', question: @question %>')