config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  
  root 'questions#index'

  devise_scope :user do
    post '/auth/register' => 'omniauth_callbacks#sign_up'
  end

  namespace :api do
    namespace :v1 do
      resources :profiles, only: :index do
        get :me, on: :collection
      end

      resources :questions, only: %i[index create show], shallow: true do
        resources :answers, only: %i[show create index]
      end
    end
  end

  resources :subscriptions, only: %i[create destroy]

  concern :votes do
    post :vote_for, on: :member
    post :vote_against, on: :member
    post :reset_vote, on: :member
  end

  concern :comments do
    resources :comments,  only: [:create]
  end

  resources :questions, shallow: true, concerns: [:votes, :comments]  do
    resources :answers, only: %i[destroy create update], concerns: [:votes, :comments] do
      post :best_answer, on: :member
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  # setup connection with the server
  mount ActionCable.server => '/cable'

  get 'search', to: 'search#search'

  # default_url_options Rails.application.config.action_mailer.default_url_options
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">

    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "QnA" %></title>
    <%= Gon::Base.render_data %>
    <%= csrf_meta_tags %>

    <%#= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

   <nav class="navbar navbar-custom navbar-static-top"> 
    <div class="container"> <div class="navbar-header">
    <button type="button" class="collapsed navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-8" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span> 
        <span class="icon-bar"></span>
        <span class="icon-bar"></span> 
    </button> 
    <a href="#" class="navbar-brand">Q&amp;A</a> 
    </div> 
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-8"> 
    <ul class="nav navbar-nav navbar-right"> 
        <li>
          <%= link_to 'Home', questions_path%>
        </li>
        <% if can?(:create, Question) %>
          <li>
            <%= link_to 'Ask question', new_question_path %>
          </li>
        <% end %>
        <li>
          <% if user_signed_in? %>
            <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
          <% else %>
            <%= link_to 'Sign in', new_user_session_path %>
          <% end %>
        </li>
         <li>
           <%= render 'search/form' %>
         </li>
      </ul>

      </div> 
    </div> 
  </nav>
   <div>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    </div>
    <%= yield %>
  </body>
</html>